# ------------------- PROJECT INFO -------------------
name: fitness_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

# ------------------- DEPENDENCIES -------------------
dependencies:
  flutter:
    sdk: flutter
  
  # UI 
  cupertino_icons: ^1.0.8

  # STATE MANAGEMENT
  flutter_bloc: ^9.1.1
  bloc: ^9.2.0
  
  # DEPENDANCY INJECTION
  get_it: ^9.2.1
  injectable: ^3.0.0
  
  # DATA
  firebase_auth: ^6.4.0
  firebase_core: ^4.7.0

  # NETWORKING
  dio: ^5.9.2

  # UTILITIES
  dartz: ^0.10.1
  go_router: ^17.2.2  
  freezed_annotation: ^3.1.0


# ------------------- DEV DEPENDENCIES -------------------
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  injectable_generator: ^3.0.2
  freezed: ^3.2.5
  build_runner: ^2.14.1


# ------------------- IMAGES & FONTS -------------------
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/onboarding/
    - assets/images/splash/
    - assets/images/

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/themes
  filename: app_images.dart
  field_prefix: null